name: object_scanpath
channels:
  - nvidia/label/cuda-12.1.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.12.12=h06a4308_0
  - cuda=12.1.0=0
  - cuda-cccl=12.1.55=0
  - cuda-command-line-tools=12.1.0=0
  - cuda-compiler=12.1.0=0
  - cuda-cudart=12.1.55=0
  - cuda-cudart-dev=12.1.55=0
  - cuda-cudart-static=12.1.55=0
  - cuda-cuobjdump=12.1.55=0
  - cuda-cupti=12.1.62=0
  - cuda-cupti-static=12.1.62=0
  - cuda-cuxxfilt=12.1.55=0
  - cuda-demo-suite=12.1.55=0
  - cuda-documentation=12.1.55=0
  - cuda-driver-dev=12.1.55=0
  - cuda-gdb=12.1.55=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-libraries-static=12.1.0=0
  - cuda-nsight=12.1.55=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=12.1.66=0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=12.1.55=0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=12.1.55=0
  - cuda-nvrtc=12.1.55=0
  - cuda-nvrtc-dev=12.1.55=0
  - cuda-nvrtc-static=12.1.55=0
  - cuda-nvtx=12.1.66=0
  - cuda-nvvp=12.1.55=0
  - cuda-opencl=12.1.56=0
  - cuda-opencl-dev=12.1.56=0
  - cuda-profiler-api=12.1.55=0
  - cuda-runtime=12.1.0=0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=12.1.0=0
  - cuda-tools=12.1.0=0
  - cuda-visual-tools=12.1.0=0
  - gds-tools=1.6.0.25=0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcublas-static=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcufft-static=11.0.2.4=0
  - libcufile=1.6.0.25=0
  - libcufile-dev=1.6.0.25=0
  - libcufile-static=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcurand-dev=10.3.2.56=0
  - libcurand-static=10.3.2.56=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusolver-static=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libcusparse-static=12.0.2.55=0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnpp-static=12.0.2.50=0
  - libnvjitlink=12.1.55=0
  - libnvjitlink-dev=12.1.55=0
  - libnvjpeg=12.1.0.39=0
  - libnvjpeg-dev=12.1.0.39=0
  - libnvjpeg-static=12.1.0.39=0
  - libnvvm-samples=12.1.55=0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nsight-compute=2023.1.0.15=0
  - openssl=3.0.12=h7f8727e_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.1.0
    - accelerate==0.27.0.dev0
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - annotated-types==0.6.0
    - apiwrapper==0.1.8
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - blis==0.7.11
    - cachetools==5.3.2
    - catalogue==2.0.10
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpathlib==0.16.0
    - confection==0.1.4
    - contourpy==1.2.0
    - cycler==0.12.1
    - cymem==2.0.8
    - datalore==0.1.0
    - datasets==2.16.1
    - dill==0.3.7
    - docker-pycreds==0.4.0
    - en-core-web-sm==3.7.1
    - et-xmlfile==1.1.0
    - evaluate==0.4.1
    - filelock==3.13.1
    - fonttools==4.47.2
    - frozenlist==1.4.1
    - fsspec==2023.10.0
    - gensim==4.3.2
    - gitdb==4.0.11
    - gitpython==3.1.41
    - google-auth==2.26.2
    - google-auth-oauthlib==1.2.0
    - grpcio==1.60.0
    - h5py==3.10.0
    - huggingface-hub==0.20.2
    - idna==3.6
    - jinja2==3.1.3
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - langcodes==3.3.0
    - llvmlite==0.42.0
    - markdown==3.5.2
    - markupsafe==2.1.3
    - matplotlib==3.8.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - murmurhash==1.0.10
    - networkx==3.2.1
    - nltk==3.8.1
    - numba==0.59.0
    - numpy==1.26.3
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - opencv-python==4.9.0.80
    - openpyxl==3.1.2
    - packaging==23.2
    - pandas==2.2.0
    - pillow==10.2.0
    - pip==23.3.1
    - preshed==3.0.9
    - protobuf==4.23.4
    - psutil==5.9.7
    - pyarrow==15.0.0
    - pyarrow-hotfix==0.6
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pydantic==2.6.3
    - pydantic-core==2.16.3
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pytz==2023.4
    - pyyaml==6.0.1
    - regex==2023.12.25
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rsa==4.9
    - safetensors==0.4.1
    - scikit-learn==1.4.0
    - scipy==1.11.4
    - sentence-transformers==2.3.1
    - sentencepiece==0.1.99
    - sentry-sdk==1.39.2
    - setproctitle==1.3.3
    - setuptools==68.2.2
    - six==1.16.0
    - smart-open==6.4.0
    - smmap==5.0.1
    - spacy==3.7.4
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.4.8
    - sympy==1.12
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - thinc==8.2.3
    - threadpoolctl==3.2.0
    - timm==0.9.12
    - tokenizers==0.15.0
    - torch==2.1.2
    - torchaudio==2.1.2
    - torchvision==0.16.2
    - tqdm==4.66.1
    - transformers==4.36.2
    - triton==2.1.0
    - typer==0.9.0
    - typing-extensions==4.9.0
    - tzdata==2023.4
    - urllib3==2.1.0
    - wandb==0.16.2
    - wasabi==1.1.2
    - weasel==0.3.4
    - werkzeug==3.0.1
    - wheel==0.41.2
    - xxhash==3.4.1
    - yacs==0.1.8
    - yarl==1.9.4
prefix: /home/anaconda3/envs/object_scanpath
